### ISSUE TITLE
How to get the access token

### ISSUE THREAD

**Issue by Vigneshkumarzx** [anoojkrishnan/ola-maps-ios-example#1]
I tried to get the access token in postman but is showing
 {
    "error": "invalid_client",
    "error_description": "Invalid client or Invalid client credentials"
}

how to resolve this

**Comment by anoojkrishnan** [comment]
Make sure that you are using the right client id. I've explained the steps in my blog.
@Vigneshkumarzx If the problem still exists, please let me know.

https://medium.com/@anooj.krishnan/bringing-navigation-to-your-ios-app-with-the-new-olamaps-sdk-217ca4f9b766
